### ISSUE TITLE
 git-rev-sync/index.js:47 throw new Error('[git-rev-sync] no git repository found')

### ISSUE THREAD

**Issue by ghost** [topheman/vanilla-es6-jspm#8]
Hi there,

Not sure if I'm missing something, but today I tried to install this repo twice, checking first that 'gulp' and 'jspm' were previously installed. However, after I complete the 'npm install' process, once I run 'gulp serve' I get:

/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:47
    throw new Error('[git-rev-sync] no git repository found');
    ^

Error: [git-rev-sync] no git repository found
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:47:11)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at _getGitDirectory (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:75:10)
    at branch (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:79:16)
    at long (/Users/Documents/repositories/vanilla-es6-jspm/node_modules/git-rev-sync/index.js:92:11)

This dependency is in the 'node_modules' folder.

Thanks for the help.

**Comment by topheman** [comment]
Hi @Vizalizer I just ran a fresh install + test + build on my laptop. No problem.

This message must be thrown from [here](https://github.com/topheman/vanilla-es6-jspm/blob/d56f4a7438d789db1ba24b9f19604b9a177d1abd/gulp/const.js#L15), where I check for the current commit hash.

If the folder where you installed `vanilla-es6-jspm` is not git versionned, it will crash.

You shouldn't have this problem if you `git clone` the source code from this repo (or your fork). Though, you might have removed the `.git` folder for some reason - if that's it, eitheir reclone the repo, or :

```shell
git init
git commit --allow-empty -m "empty commit"
```

If you really don't want any git versionning, you can checkout [this helper](https://github.com/topheman/webpack-babel-starter/blob/master/common.js#L54) I made on an other project, that will let you bypass this kind of error.
